### ISSUE TITLE
Getting logged out after massimporting unitypackages from local Server.

### ISSUE THREAD

**Issue by wolfswolke** [HakuSystems/naxokit#50]
You get no error. When you Import them and pressed SAVEPASSWORD it will log you back in if the auth_api.json exists. If you did not it wont log you back in.
![image](https://user-images.githubusercontent.com/34097612/187762348-3eeb7854-ac23-428e-8794-0d7839be5ac6.png)
I used 2 packages (Shaders) on my SMB Server and got the same result every time.
![image](https://user-images.githubusercontent.com/34097612/187762715-13756abc-3217-4497-959f-960606d5886a.png)

**Comment by HakuSystems** [comment]
Have send you @wolfswolke a new unitypackage this should fix the issue (worked for me) please respond to this.

**Comment by HakuSystems** [comment]
@wolfswolke Still no reply i need answers haha

**Comment by wolfswolke** [comment]
Sry it works now ^^
