### ISSUE TITLE
MissingShader finder

### ISSUE THREAD

**Issue by wolfswolke** [HakuSystems/naxokit#51]
Most shaders use keywoards in theyr .mat file and a GUID.
It would be nice if there was a Feature that can show me what shader was used so i dont have to search everytime which one i forgot to import.
![image](https://user-images.githubusercontent.com/34097612/187764616-103cf2d7-20de-459b-8e13-f0bee98b04e5.png)
![image](https://user-images.githubusercontent.com/34097612/187764738-10aeb1ea-d584-4b20-9af3-15e67eb7231e.png)

**Comment by wolfswolke** [comment]
Could be solved by reading stringTagMap: ~ -OriginalShader.

**Comment by HakuSystems** [comment]
i have absolutely no idea how to implement that
