### ISSUE TITLE
Feature: Templets

### ISSUE THREAD

**Issue by wolfswolke** [HakuSystems/naxokit#52]
Either a Import Templet or Project Templet.
Import Templet:
Add all Packages you need and after that you can press something like "Import Templet XYZ" and it imports all of them from the saved location.

Project Templet:
Create a Templet Project and save it as a unitypackage file which then gets imported with a Button. That would harder Because packages like VRC save things in the Project Root Folder and in the Unity APPDATA Folder...

**Comment by HakuSystems** [comment]
ADDED
