### ISSUE TITLE
Feature: Fixing Amatures.

### ISSUE THREAD

**Issue by wolfswolke** [HakuSystems/naxokit#57]
Some idiots rename the howl Amature so you have to rename every item...
Please add something so we can One click rename it...
![image](https://user-images.githubusercontent.com/34097612/190505359-6af597dd-2072-4597-b62a-8e8fea33f5e5.png)

**Comment by wolfswolke** [comment]
Idea. Click the ROOT object of the "Pfusch" and then add like a box where you can say remove this from the tree.
Like: Hip(XYZ), Spin(XYZ)         REMOVE (XYZ)

**Comment by HakuSystems** [comment]
VRCHAT Related
