### ISSUE TITLE
Bug: Prefab Utility doesnt exist.

### ISSUE THREAD

**Issue by wolfswolke** [HakuSystems/naxokit#63]
When trying to upload this error occures. (Tested with WORLD SDK. Im not sure if this happnes on Avatar SDK but i think it does.)
![image](https://user-images.githubusercontent.com/34097612/197887158-ea224994-9619-470b-a431-dbef0b1ce162.png)
Temporary fix for me:
Comment out the Green Line
![image](https://user-images.githubusercontent.com/34097612/197887083-2db7fd6c-f5f1-4dbb-82a0-4daace8c96ae.png)

**Comment by HakuSystems** [comment]
this is nanoSDK/VRCHAT related, we dont support anything nanoSDK/VRCHAT related anymore
