### ISSUE TITLE
Bug: Android Build not working

### ISSUE THREAD

**Issue by wolfswolke** [HakuSystems/naxokit#64]
After switching to Android (Quest) 
Error occures when Publishing a Avatar or World.
![image](https://user-images.githubusercontent.com/34097612/197893141-8ce29ba9-90ef-499f-a687-10763b6ed91d.png)

**Comment by HakuSystems** [comment]
naxokit is not designed or intended for use with the Android for Unity platform. We recommend using an alternative solution for any Android for Unity development needs.
